In [1]:
import pandas as pd
df = pd.read_csv('cases.txt')

In [4]:
df.columns

Index(['caseid', 'subjectid', 'casestart', 'caseend', 'anestart', 'aneend',
       'opstart', 'opend', 'adm', 'dis', 'icu_days', 'death_inhosp', 'age',
       'sex', 'height', 'weight', 'bmi', 'asa', 'emop', 'department', 'optype',
       'dx', 'opname', 'approach', 'position', 'ane_type', 'preop_htn',
       'preop_dm', 'preop_ecg', 'preop_pft', 'preop_hb', 'preop_plt',
       'preop_pt', 'preop_aptt', 'preop_na', 'preop_k', 'preop_gluc',
       'preop_alb', 'preop_ast', 'preop_alt', 'preop_bun', 'preop_cr',
       'preop_ph', 'preop_hco3', 'preop_be', 'preop_pao2', 'preop_paco2',
       'preop_sao2', 'cormack', 'airway', 'tubesize', 'dltubesize', 'lmasize',
       'iv1', 'iv2', 'aline1', 'aline2', 'cline1', 'cline2', 'intraop_ebl',
       'intraop_uo', 'intraop_rbc', 'intraop_ffp', 'intraop_crystalloid',
       'intraop_colloid', 'intraop_ppf', 'intraop_mdz', 'intraop_ftn',
       'intraop_rocu', 'intraop_vecu', 'intraop_eph', 'intraop_phe',
       'intraop_epi', 'intraop_ca'],
      dtype='object')

In [6]:
df.groupby('optype').count()

,caseid,subjectid,casestart,caseend,anestart,aneend,opstart,opend,adm,dis,...,intraop_colloid,intraop_ppf,intraop_mdz,intraop_ftn,intraop_rocu,intraop_vecu,intraop_eph,intraop_phe,intraop_epi,intraop_ca
optype,,,,,,,,,,,,,,,,,,,,,
Biliary/Pancreas,812,812,812,812,812,812,812,812,812,812,...,812,812,812,812,812,812,812,812,812,812
Breast,434,434,434,434,434,434,434,434,434,434,...,434,434,434,434,434,434,434,434,434,434
Colorectal,1350,1350,1350,1350,1350,1350,1350,1350,1350,1350,...,1350,1350,1350,1350,1350,1350,1350,1350,1350,1350
Hepatic,258,258,258,258,258,258,258,258,258,258,...,258,258,258,258,258,258,258,258,258,258
Major resection,584,584,584,584,584,584,584,584,584,584,...,584,584,584,584,584,584,584,584,584,584
Minor resection,553,553,553,553,553,553,553,553,553,553,...,553,553,553,553,553,553,553,553,553,553
Others,799,799,799,799,799,799,799,799,799,799,...,799,799,799,799,799,799,799,799,799,799
Stomach,676,676,676,676,676,676,676,676,676,676,...,676,676,676,676,676,676,676,676,676,676
Thyroid,257,257,257,257,257,257,257,257,257,257,...,257,257,257,257,257,257,257,257,257,257
Transplantation,403,403,403,403,403,403,403,403,403,403,...,403,403,403,403,403,403,403,403,403,403
Vascular,262,262,262,262,262,262,262,262,262,262,...,262,262,262,262,262,262,262,262,262,262